title: BCySec Blog
description: Articles from Bocconi Students Cyber Security Association
url: "https://bcysec.github.io"
baseurl: "/bcysec-website"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /blog/:title/

plugins:
  - jekyll-feed

# Files/folders Jekyll should leave alone or not publish
exclude:
  - README.md
  - How-to-publish-BCySec-website-free.md
  - How-to-publish-a-blog-post.md
